"""add system prompt to agents

Revision ID: 1a528b523d8a
Revises: 80251ce45937
Create Date: 2026-08-21 14:02:47.385331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a528b523d8a'
down_revision: Union[str, Sequence[str], None] = '80251ce45937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'agents',
        sa.Column(
            'system_prompt',
            sa.Text(),
            nullable=False,
            server_default=''
        )
    )

    op.alter_column(
        'agents',
        'system_prompt',
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'system_prompt')
    # ### end Alembic commands ###
