"""link agents to knowledge bases

Revision ID: 4fd77378b90b
Revises: 4c85fe1c2463
Create Date: 2026-08-24 16:26:35.205974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd77378b90b'
down_revision: Union[str, Sequence[str], None] = '4c85fe1c2463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('knowledge_base_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agents', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'knowledge_base_id')
    # ### end Alembic commands ###
